---
- hosts: do_jenkins

  tasks:
    - name: Download docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '711'
    - name: Test connectivity
      ping:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Enabling the EPEL repo
      yum:
        name:
          - epel-release

    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Add Docker CE repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Start service Docker, if not started
      service:
        name: docker
        state: started
    
    - name: Get GID of docker
      getent:
        database: group
        key: docker
    
    - debug:
        var: getent_group.docker[1]

    - name: Install Python PIP
      yum:
        name:
          - python-pip

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Copy files of jenkins on the control node to the tmp on the remote hosts
      copy:
        src: jenkins
        dest: /tmp
    
    - name: Build the Jenkins CI image
      docker_image:
        name: my-jenkins
        build:
          path: /tmp/jenkins
          args:
            docker_gid: "{{ getent_group.docker[1] }}"
          pull: yes
        source: build

    - name: Jenkins container
      docker:
        name: jenkins
        image: my-jenkins
        state: started
        expose:
          - 8080
          - 50000
        volume:
          - 'jenkins_home:/var/jenkins_home'
          - './casc_configs:/var/jenkins_home/casc_configs'
          - '/var/run/docker.sock:/var/run/docker.sock'


