---
- hosts: do_jenkins

  tasks:
    - name: Test connectivity
      ping:

    - name: Get GID of docker
      getent:
        database: group
        key: docker
    
    - debug:
        var: getent_group.docker[1]

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Add Docker CE repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Start service Docker, if not started
      service:
        name: docker
        state: started

    - name: Install required packages for Jenkins
      yum:
        name:
          - git
          - java-1.8.0-openjdk-devel

    - name: Add Jenkins repository
      shell: yum-config-manager --add-repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: Import key for Jenkins repository
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name:
          - jenkins

    - name: Appending the group 'docker' to the jenkins user's groups
      user:
        name: jenkins
        group: docker
        append: yes

    - name: Start service Jenkins, if not started
      service:
        name: jenkins
        state: restarted

    - name: Wait for port 8000 to become open on the host, don't start checking for 10 seconds
      wait_for:
        port: 8080
        delay: 10

    - stat:
        path: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_default_password_file_status

    - name: Get the default password of Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_default_password_results
      when: jenkins_default_password_file_status.stat.exists

    - name: Print Jenkins default password
      debug:
        msg: "{{ jenkins_default_password_results.stdout }}"
      when: jenkins_default_password_file_status.stat.exists
