---
- hosts: do_jenkins

  tasks:
    - name: Test connectivity
      ping:

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Add Docker CE repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
