---
- hosts: do_docker
  vars:
    upgrade_all_packages: false

  tasks:
    - name: Test connectivity
      ping:

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    
    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: upgrade_all_packages

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes 
        state: latest

    - name: Start service Docker, if not started
      service:
        name: docker
        state: started
    
    - name: Install Python PIP
      apt:
        name:
          - python3-pip
          - python3-setuptools

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker >= 1.8.0
          - PyYAML >= 3.11
          - docker-compose >= 1.7.0
